### ISSUE TITLE
Response errors don't go up the stream

### ISSUE THREAD

**Issue by yardensk** [Bandwidth/node-bandwidth#126]
Let's say im sending an SMS message with a wrong field 
```node
{'from':'..','to':'...','message':{'text':'...','notgood':'....'}}
```
The error I get after using `client.Message.sendGroup(...).catch(function(err){});` doesnt reflect the actual error and only says: `ResponseError`

This is a serious issue as it prevents from debugging the code properly

it should be fixed in the `lib/client.js` `makeRequest` function probably

**Comment by dtolb** [comment]
@yardensk I pushed a change up to the [local-v2](https://github.com/bandwidthcom/node-bandwidth/pull/127/files#diff-50cfa59973c04321b5da0c6da0fdf4feL19) branch that should return the error for ya.

```js
const main = async () => {
	var client = new b({
		userId : 'u-adf',
		apiToken : 't-asdf',
		apiSecret : 'asdf'
	});
	//let apps = (await client.Application.list({size: 1000})).applications;
	const groupMessageParams = {
		to : ['+123', '+134'],
		from: '+18707104430',
		text: 'GROUPPPPPP MESSSAGE AWAY',
		catch: 'theFever',
		media : ["https://s3.amazonaws.com/bw-v2-api/demo.jpg"]
	}
	try {
		let message = await client.Message.sendGroup(groupMessageParams);
		console.log(message);
	}
	catch (error) {
		console.log(error);
	}
}
```

```
{ Error
    at handleResponse (/Users/dtolbert/code/sdks/node-bandwidth/lib/client.js:22:10)
    at tryCatcher (/Users/dtolbert/code/sdks/node-bandwidth/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/dtolbert/code/sdks/node-bandwidth/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/dtolbert/code/sdks/node-bandwidth/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/dtolbert/code/sdks/node-bandwidth/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/dtolbert/code/sdks/node-bandwidth/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/dtolbert/code/sdks/node-bandwidth/node_modules/bluebird/js/release/promise.js:636:18)
    at Request._callback (/Users/dtolbert/code/sdks/node-bandwidth/node_modules/bluebird/js/release/nodeback.js:42:21)
    at Request.self.callback (/Users/dtolbert/code/sdks/node-bandwidth/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/dtolbert/code/sdks/node-bandwidth/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/dtolbert/code/sdks/node-bandwidth/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:293:19)
  name: 'UnexpectedResponseError',
  message:
   { type: 'invalid-property-name',
     description: 'Unrecognized JSON property: \'catch\' near line 1, column 104' },
  statusCode: 400 }
```

Try that out and let me know what ya think!

**Comment by yardensk** [comment]
works great thanks!
