### ISSUE TITLE
Media tests break on node v8.1.2

### ISSUE THREAD

**Issue by dtolb** [Bandwidth/node-bandwidth#130]
Steps to recreate
* Clone fresh repo
* Ensure you're on master branch
* Ensure you're using `v8.x` of node. [Changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.2.1)
* `npm install`
* `npm test`
* Watch as media tests fail
* Or run
```
$ mocha -R spec test/media-test.js
```

```
  Media API
    global methods
      1) should upload a media file (Buffer), Promise
      2) should upload a media file (Buffer) with content type, Promise
      3) should upload a media file (Buffer), callback
      4) should upload a media file (Buffer) with content type, callback
      5) should upload a media file (stream), Promise
      6) should upload a media file (stream) with content type, Promise
      7) should upload a media file (file), Promise
      8) should upload a media file (file) with content type, Promise
      9) should throw error if uploaded data is invalid
      10) should throw error if fs.stat failed
      ✓ should download a media file
      ✓ should list media files
      ✓ should remove a media file


  3 passing (68ms)
  10 failing

  1) Media API global methods should upload a media file (Buffer), Promise:
     Error: Nock: No match for request PUT https://api.catapult.inetwork.com/v1/users/fakeUserId/media/file1 1234567890
      at end (node_modules/nock/lib/request_overrider.js:259:17)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:159:7)
      at Request.end (node_modules/request/request.js:1528:14)
      at Readable.onend (_stream_readable.js:584:10)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) Media API global methods should upload a media file (Buffer) with content type, Promise:
     Error: Nock: No match for request PUT https://api.catapult.inetwork.com/v1/users/fakeUserId/media/file2 1234567890
      at end (node_modules/nock/lib/request_overrider.js:259:17)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:159:7)
      at Request.end (node_modules/request/request.js:1528:14)
      at Readable.onend (_stream_readable.js:584:10)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  3) Media API global methods should upload a media file (Buffer), callback:
     Error: Nock: No match for request PUT https://api.catapult.inetwork.com/v1/users/fakeUserId/media/file1 1234567890
      at end (node_modules/nock/lib/request_overrider.js:259:17)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:159:7)
      at Request.end (node_modules/request/request.js:1528:14)
      at Readable.onend (_stream_readable.js:584:10)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  4) Media API global methods should upload a media file (Buffer) with content type, callback:
     Error: Nock: No match for request PUT https://api.catapult.inetwork.com/v1/users/fakeUserId/media/file2 1234567890
      at end (node_modules/nock/lib/request_overrider.js:259:17)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:159:7)
      at Request.end (node_modules/request/request.js:1528:14)
      at Readable.onend (_stream_readable.js:584:10)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  5) Media API global methods should upload a media file (stream), Promise:
     Error: Nock: No match for request PUT https://api.catapult.inetwork.com/v1/users/fakeUserId/media/file1 1234567890
      at end (node_modules/nock/lib/request_overrider.js:259:17)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:159:7)
      at Request.end (node_modules/request/request.js:1528:14)
      at Readable.onend (_stream_readable.js:584:10)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  6) Media API global methods should upload a media file (stream) with content type, Promise:
     Error: Nock: No match for request PUT https://api.catapult.inetwork.com/v1/users/fakeUserId/media/file2 1234567890
      at end (node_modules/nock/lib/request_overrider.js:259:17)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:159:7)
      at Request.end (node_modules/request/request.js:1528:14)
      at Readable.onend (_stream_readable.js:584:10)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  7) Media API global methods should upload a media file (file), Promise:
     Error: Nock: No match for request PUT https://api.catapult.inetwork.com/v1/users/fakeUserId/media/file1 1234567890
      at end (node_modules/nock/lib/request_overrider.js:259:17)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:159:7)
      at Request.end (node_modules/request/request.js:1528:14)
      at ReadStream.onend (_stream_readable.js:584:10)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  8) Media API global methods should upload a media file (file) with content type, Promise:
     Error: Nock: No match for request PUT https://api.catapult.inetwork.com/v1/users/fakeUserId/media/file2 1234567890
      at end (node_modules/nock/lib/request_overrider.js:259:17)
      at OverriddenClientRequest.RequestOverrider.req.end (node_modules/nock/lib/request_overrider.js:159:7)
      at Request.end (node_modules/request/request.js:1528:14)
      at ReadStream.onend (_stream_readable.js:584:10)
      at endReadableNT (_stream_readable.js:1045:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  9) Media API global methods should throw error if uploaded data is invalid:
     Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
      at test/media-test.js:111:5
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise.errorAdapter [as _rejectionHandler0] (node_modules/bluebird/js/release/nodeify.js:35:34)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:566:21)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:689:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)

  10) Media API global methods should throw error if fs.stat failed:
     Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
      at test/media-test.js:120:5
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Promise.errorAdapter [as _rejectionHandler0] (node_modules/bluebird/js/release/nodeify.js:35:34)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:566:21)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:689:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by dtolb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [NodeJS v8 compliance... Right now tests fail when using node v8.x](https://trello.com/c/FoOxoOk3/183-nodejs-v8-compliance-right-now-tests-fail-when-using-node-v8x)
